/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


enum Gender {
  Gender_MALE = 0,
  Gender_FEMALE = 1,
  Gender_UNKNOW = 2
};

enum TaskStat {
  TaskStat_NONE = 0,
  TaskStat_ACCEPT = 1,
  TaskStat_REJECT = 2
};

enum TasklistType {
  TasklistType_ALL = 0,
  TasklistType_RECOMMEND = 1,
  TasklistType_NEARBY = 2,
  TasklistType_FOLLOW = 3,
  TasklistType_FAVOURITES = 4
};

typedef int64_t timestamp;

@interface AuthRequest : NSObject <NSCoding> {
  NSString * __client_id;
  NSString * __client_serect;

  BOOL __client_id_isset;
  BOOL __client_serect_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=client_id, setter=setClient_id:) NSString * client_id;
@property (nonatomic, retain, getter=client_serect, setter=setClient_serect:) NSString * client_serect;
#endif

- (id) initWithClient_id: (NSString *) client_id client_serect: (NSString *) client_serect;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) client_id;
- (void) setClient_id: (NSString *) client_id;
- (BOOL) client_idIsSet;

- (NSString *) client_serect;
- (void) setClient_serect: (NSString *) client_serect;
- (BOOL) client_serectIsSet;

@end

@interface AuthResponse : NSObject <NSCoding> {
  int64_t __uid;
  NSString * __name;
  NSString * __access_token;
  NSString * __refresh_token;
  int64_t __expire_time;

  BOOL __uid_isset;
  BOOL __name_isset;
  BOOL __access_token_isset;
  BOOL __refresh_token_isset;
  BOOL __expire_time_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=uid, setter=setUid:) int64_t uid;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=access_token, setter=setAccess_token:) NSString * access_token;
@property (nonatomic, retain, getter=refresh_token, setter=setRefresh_token:) NSString * refresh_token;
@property (nonatomic, getter=expire_time, setter=setExpire_time:) int64_t expire_time;
#endif

- (id) initWithUid: (int64_t) uid name: (NSString *) name access_token: (NSString *) access_token refresh_token: (NSString *) refresh_token expire_time: (int64_t) expire_time;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) uid;
- (void) setUid: (int64_t) uid;
- (BOOL) uidIsSet;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (NSString *) access_token;
- (void) setAccess_token: (NSString *) access_token;
- (BOOL) access_tokenIsSet;

- (NSString *) refresh_token;
- (void) setRefresh_token: (NSString *) refresh_token;
- (BOOL) refresh_tokenIsSet;

- (int64_t) expire_time;
- (void) setExpire_time: (int64_t) expire_time;
- (BOOL) expire_timeIsSet;

@end

@interface UserInfo : NSObject <NSCoding> {
  NSString * __name;
  int __gender;
  NSString * __org;
  NSString * __job;
  NSString * __small_avator;
  NSString * __big_avator;
  NSString * __intro;

  BOOL __name_isset;
  BOOL __gender_isset;
  BOOL __org_isset;
  BOOL __job_isset;
  BOOL __small_avator_isset;
  BOOL __big_avator_isset;
  BOOL __intro_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=gender, setter=setGender:) int gender;
@property (nonatomic, retain, getter=org, setter=setOrg:) NSString * org;
@property (nonatomic, retain, getter=job, setter=setJob:) NSString * job;
@property (nonatomic, retain, getter=small_avator, setter=setSmall_avator:) NSString * small_avator;
@property (nonatomic, retain, getter=big_avator, setter=setBig_avator:) NSString * big_avator;
@property (nonatomic, retain, getter=intro, setter=setIntro:) NSString * intro;
#endif

- (id) initWithName: (NSString *) name gender: (int) gender org: (NSString *) org job: (NSString *) job small_avator: (NSString *) small_avator big_avator: (NSString *) big_avator intro: (NSString *) intro;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (int) gender;
- (void) setGender: (int) gender;
- (BOOL) genderIsSet;

- (NSString *) org;
- (void) setOrg: (NSString *) org;
- (BOOL) orgIsSet;

- (NSString *) job;
- (void) setJob: (NSString *) job;
- (BOOL) jobIsSet;

- (NSString *) small_avator;
- (void) setSmall_avator: (NSString *) small_avator;
- (BOOL) small_avatorIsSet;

- (NSString *) big_avator;
- (void) setBig_avator: (NSString *) big_avator;
- (BOOL) big_avatorIsSet;

- (NSString *) intro;
- (void) setIntro: (NSString *) intro;
- (BOOL) introIsSet;

@end

@interface TaskBasic : NSObject <NSCoding> {
  int64_t __tid;
  NSString * __name;
  int64_t __owner;
  NSString * __intro;
  int64_t __plan_num;
  int64_t __begin_time;
  int64_t __end_time;
  int64_t __apply_num;
  int64_t __invite_num;
  int64_t __accept_num;

  BOOL __tid_isset;
  BOOL __name_isset;
  BOOL __owner_isset;
  BOOL __intro_isset;
  BOOL __plan_num_isset;
  BOOL __begin_time_isset;
  BOOL __end_time_isset;
  BOOL __apply_num_isset;
  BOOL __invite_num_isset;
  BOOL __accept_num_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=tid, setter=setTid:) int64_t tid;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=owner, setter=setOwner:) int64_t owner;
@property (nonatomic, retain, getter=intro, setter=setIntro:) NSString * intro;
@property (nonatomic, getter=plan_num, setter=setPlan_num:) int64_t plan_num;
@property (nonatomic, getter=begin_time, setter=setBegin_time:) int64_t begin_time;
@property (nonatomic, getter=end_time, setter=setEnd_time:) int64_t end_time;
@property (nonatomic, getter=apply_num, setter=setApply_num:) int64_t apply_num;
@property (nonatomic, getter=invite_num, setter=setInvite_num:) int64_t invite_num;
@property (nonatomic, getter=accept_num, setter=setAccept_num:) int64_t accept_num;
#endif

- (id) initWithTid: (int64_t) tid name: (NSString *) name owner: (int64_t) owner intro: (NSString *) intro plan_num: (int64_t) plan_num begin_time: (int64_t) begin_time end_time: (int64_t) end_time apply_num: (int64_t) apply_num invite_num: (int64_t) invite_num accept_num: (int64_t) accept_num;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) tid;
- (void) setTid: (int64_t) tid;
- (BOOL) tidIsSet;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (int64_t) owner;
- (void) setOwner: (int64_t) owner;
- (BOOL) ownerIsSet;

- (NSString *) intro;
- (void) setIntro: (NSString *) intro;
- (BOOL) introIsSet;

- (int64_t) plan_num;
- (void) setPlan_num: (int64_t) plan_num;
- (BOOL) plan_numIsSet;

- (int64_t) begin_time;
- (void) setBegin_time: (int64_t) begin_time;
- (BOOL) begin_timeIsSet;

- (int64_t) end_time;
- (void) setEnd_time: (int64_t) end_time;
- (BOOL) end_timeIsSet;

- (int64_t) apply_num;
- (void) setApply_num: (int64_t) apply_num;
- (BOOL) apply_numIsSet;

- (int64_t) invite_num;
- (void) setInvite_num: (int64_t) invite_num;
- (BOOL) invite_numIsSet;

- (int64_t) accept_num;
- (void) setAccept_num: (int64_t) accept_num;
- (BOOL) accept_numIsSet;

@end

@interface TaskExt : NSObject <NSCoding> {
  NSArray * __user_apply_list;
  NSArray * __user_invite_list;
  NSArray * __user_invite_stat;
  NSArray * __user_accept_list;

  BOOL __user_apply_list_isset;
  BOOL __user_invite_list_isset;
  BOOL __user_invite_stat_isset;
  BOOL __user_accept_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=user_apply_list, setter=setUser_apply_list:) NSArray * user_apply_list;
@property (nonatomic, retain, getter=user_invite_list, setter=setUser_invite_list:) NSArray * user_invite_list;
@property (nonatomic, retain, getter=user_invite_stat, setter=setUser_invite_stat:) NSArray * user_invite_stat;
@property (nonatomic, retain, getter=user_accept_list, setter=setUser_accept_list:) NSArray * user_accept_list;
#endif

- (id) initWithUser_apply_list: (NSArray *) user_apply_list user_invite_list: (NSArray *) user_invite_list user_invite_stat: (NSArray *) user_invite_stat user_accept_list: (NSArray *) user_accept_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSArray *) user_apply_list;
- (void) setUser_apply_list: (NSArray *) user_apply_list;
- (BOOL) user_apply_listIsSet;

- (NSArray *) user_invite_list;
- (void) setUser_invite_list: (NSArray *) user_invite_list;
- (BOOL) user_invite_listIsSet;

- (NSArray *) user_invite_stat;
- (void) setUser_invite_stat: (NSArray *) user_invite_stat;
- (BOOL) user_invite_statIsSet;

- (NSArray *) user_accept_list;
- (void) setUser_accept_list: (NSArray *) user_accept_list;
- (BOOL) user_accept_listIsSet;

@end

@interface TaskInfo : NSObject <NSCoding> {
  TaskBasic * __basic;
  TaskExt * __ext;

  BOOL __basic_isset;
  BOOL __ext_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=basic, setter=setBasic:) TaskBasic * basic;
@property (nonatomic, retain, getter=ext, setter=setExt:) TaskExt * ext;
#endif

- (id) initWithBasic: (TaskBasic *) basic ext: (TaskExt *) ext;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (TaskBasic *) basic;
- (void) setBasic: (TaskBasic *) basic;
- (BOOL) basicIsSet;

- (TaskExt *) ext;
- (void) setExt: (TaskExt *) ext;
- (BOOL) extIsSet;

@end

@interface typeConstants : NSObject {
}
@end
