/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


enum UserGender {
  UserGender_Unknown = 0,
  UserGender_Male = 1,
  UserGender_Female = 2
};

enum UserListType {
  UserListType_All = 0,
  UserListType_Recommend = 1,
  UserListType_Nearby = 2,
  UserListType_Following = 3,
  UserListType_Followed = 4,
  UserListType_Friends = 5
};

enum TaskState {
  TaskState_Normal = 0,
  TaskState_Interested = 1,
  TaskState_Accepted = 2,
  TaskState_Applied = 3,
  TaskState_Invited = 4,
  TaskState_Rejected = 5
};

enum TaskListType {
  TaskListType_All = 0,
  TaskListType_Recommend = 1,
  TaskListType_Nearby = 2,
  TaskListType_Following = 3
};

enum MsgType {
  MsgType_All = 0,
  MsgType_System = 1,
  MsgType_Friends = 2,
  MsgType_Stranger = 4,
  MsgType_Unread = 8
};

enum FeedType {
  FeedType_All = 0,
  FeedType_Text = 1,
  FeedType_Article = 2,
  FeedType_Pic = 3,
  FeedType_Activity = 4
};

typedef int64_t timestamp;

@interface AuthRequest : NSObject <NSCoding> {
  int64_t __client_id;
  NSString * __client_secret;
  NSString * __mail;
  NSString * __password;

  BOOL __client_id_isset;
  BOOL __client_secret_isset;
  BOOL __mail_isset;
  BOOL __password_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=client_id, setter=setClient_id:) int64_t client_id;
@property (nonatomic, retain, getter=client_secret, setter=setClient_secret:) NSString * client_secret;
@property (nonatomic, retain, getter=mail, setter=setMail:) NSString * mail;
@property (nonatomic, retain, getter=password, setter=setPassword:) NSString * password;
#endif

- (id) initWithClient_id: (int64_t) client_id client_secret: (NSString *) client_secret mail: (NSString *) mail password: (NSString *) password;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) client_id;
- (void) setClient_id: (int64_t) client_id;
- (BOOL) client_idIsSet;

- (NSString *) client_secret;
- (void) setClient_secret: (NSString *) client_secret;
- (BOOL) client_secretIsSet;

- (NSString *) mail;
- (void) setMail: (NSString *) mail;
- (BOOL) mailIsSet;

- (NSString *) password;
- (void) setPassword: (NSString *) password;
- (BOOL) passwordIsSet;

@end

@interface AuthResponse : NSObject <NSCoding> {
  NSString * __access_token;
  timestamp __expire_in;
  int64_t __user_id;

  BOOL __access_token_isset;
  BOOL __expire_in_isset;
  BOOL __user_id_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=access_token, setter=setAccess_token:) NSString * access_token;
@property (nonatomic, getter=expire_in, setter=setExpire_in:) timestamp expire_in;
@property (nonatomic, getter=user_id, setter=setUser_id:) int64_t user_id;
#endif

- (id) initWithAccess_token: (NSString *) access_token expire_in: (timestamp) expire_in user_id: (int64_t) user_id;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) access_token;
- (void) setAccess_token: (NSString *) access_token;
- (BOOL) access_tokenIsSet;

- (timestamp) expire_in;
- (void) setExpire_in: (timestamp) expire_in;
- (BOOL) expire_inIsSet;

- (int64_t) user_id;
- (void) setUser_id: (int64_t) user_id;
- (BOOL) user_idIsSet;

@end

@interface UserBasic : NSObject <NSCoding> {
  int64_t __user_id;
  NSString * __name;
  int __gender;
  NSString * __org;
  NSString * __job;
  NSString * __avator;

  BOOL __user_id_isset;
  BOOL __name_isset;
  BOOL __gender_isset;
  BOOL __org_isset;
  BOOL __job_isset;
  BOOL __avator_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=user_id, setter=setUser_id:) int64_t user_id;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=gender, setter=setGender:) int gender;
@property (nonatomic, retain, getter=org, setter=setOrg:) NSString * org;
@property (nonatomic, retain, getter=job, setter=setJob:) NSString * job;
@property (nonatomic, retain, getter=avator, setter=setAvator:) NSString * avator;
#endif

- (id) initWithUser_id: (int64_t) user_id name: (NSString *) name gender: (int) gender org: (NSString *) org job: (NSString *) job avator: (NSString *) avator;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) user_id;
- (void) setUser_id: (int64_t) user_id;
- (BOOL) user_idIsSet;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (int) gender;
- (void) setGender: (int) gender;
- (BOOL) genderIsSet;

- (NSString *) org;
- (void) setOrg: (NSString *) org;
- (BOOL) orgIsSet;

- (NSString *) job;
- (void) setJob: (NSString *) job;
- (BOOL) jobIsSet;

- (NSString *) avator;
- (void) setAvator: (NSString *) avator;
- (BOOL) avatorIsSet;

@end

@interface UserExt : NSObject <NSCoding> {
  NSString * __intro;
  NSArray * __following;
  NSArray * __followed;

  BOOL __intro_isset;
  BOOL __following_isset;
  BOOL __followed_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=intro, setter=setIntro:) NSString * intro;
@property (nonatomic, retain, getter=following, setter=setFollowing:) NSArray * following;
@property (nonatomic, retain, getter=followed, setter=setFollowed:) NSArray * followed;
#endif

- (id) initWithIntro: (NSString *) intro following: (NSArray *) following followed: (NSArray *) followed;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) intro;
- (void) setIntro: (NSString *) intro;
- (BOOL) introIsSet;

- (NSArray *) following;
- (void) setFollowing: (NSArray *) following;
- (BOOL) followingIsSet;

- (NSArray *) followed;
- (void) setFollowed: (NSArray *) followed;
- (BOOL) followedIsSet;

@end

@interface User : NSObject <NSCoding> {
  UserBasic * __basic;
  UserExt * __ext;

  BOOL __basic_isset;
  BOOL __ext_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=basic, setter=setBasic:) UserBasic * basic;
@property (nonatomic, retain, getter=ext, setter=setExt:) UserExt * ext;
#endif

- (id) initWithBasic: (UserBasic *) basic ext: (UserExt *) ext;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (UserBasic *) basic;
- (void) setBasic: (UserBasic *) basic;
- (BOOL) basicIsSet;

- (UserExt *) ext;
- (void) setExt: (UserExt *) ext;
- (BOOL) extIsSet;

@end

@interface TaskBasic : NSObject <NSCoding> {
  int64_t __task_id;
  int __state;
  NSString * __title;
  NSString * __intro;
  NSString * __cover;
  UserBasic * __sponsor;

  BOOL __task_id_isset;
  BOOL __state_isset;
  BOOL __title_isset;
  BOOL __intro_isset;
  BOOL __cover_isset;
  BOOL __sponsor_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=task_id, setter=setTask_id:) int64_t task_id;
@property (nonatomic, getter=state, setter=setState:) int state;
@property (nonatomic, retain, getter=title, setter=setTitle:) NSString * title;
@property (nonatomic, retain, getter=intro, setter=setIntro:) NSString * intro;
@property (nonatomic, retain, getter=cover, setter=setCover:) NSString * cover;
@property (nonatomic, retain, getter=sponsor, setter=setSponsor:) UserBasic * sponsor;
#endif

- (id) initWithTask_id: (int64_t) task_id state: (int) state title: (NSString *) title intro: (NSString *) intro cover: (NSString *) cover sponsor: (UserBasic *) sponsor;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) task_id;
- (void) setTask_id: (int64_t) task_id;
- (BOOL) task_idIsSet;

- (int) state;
- (void) setState: (int) state;
- (BOOL) stateIsSet;

- (NSString *) title;
- (void) setTitle: (NSString *) title;
- (BOOL) titleIsSet;

- (NSString *) intro;
- (void) setIntro: (NSString *) intro;
- (BOOL) introIsSet;

- (NSString *) cover;
- (void) setCover: (NSString *) cover;
- (BOOL) coverIsSet;

- (UserBasic *) sponsor;
- (void) setSponsor: (UserBasic *) sponsor;
- (BOOL) sponsorIsSet;

@end

@interface TaskExt : NSObject <NSCoding> {
  NSArray * __interested_list;
  NSArray * __accepted_list;
  NSArray * __invited_list;
  NSArray * __applied_list;

  BOOL __interested_list_isset;
  BOOL __accepted_list_isset;
  BOOL __invited_list_isset;
  BOOL __applied_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=interested_list, setter=setInterested_list:) NSArray * interested_list;
@property (nonatomic, retain, getter=accepted_list, setter=setAccepted_list:) NSArray * accepted_list;
@property (nonatomic, retain, getter=invited_list, setter=setInvited_list:) NSArray * invited_list;
@property (nonatomic, retain, getter=applied_list, setter=setApplied_list:) NSArray * applied_list;
#endif

- (id) initWithInterested_list: (NSArray *) interested_list accepted_list: (NSArray *) accepted_list invited_list: (NSArray *) invited_list applied_list: (NSArray *) applied_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSArray *) interested_list;
- (void) setInterested_list: (NSArray *) interested_list;
- (BOOL) interested_listIsSet;

- (NSArray *) accepted_list;
- (void) setAccepted_list: (NSArray *) accepted_list;
- (BOOL) accepted_listIsSet;

- (NSArray *) invited_list;
- (void) setInvited_list: (NSArray *) invited_list;
- (BOOL) invited_listIsSet;

- (NSArray *) applied_list;
- (void) setApplied_list: (NSArray *) applied_list;
- (BOOL) applied_listIsSet;

@end

@interface Task : NSObject <NSCoding> {
  TaskBasic * __basic;
  TaskExt * __ext;

  BOOL __basic_isset;
  BOOL __ext_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=basic, setter=setBasic:) TaskBasic * basic;
@property (nonatomic, retain, getter=ext, setter=setExt:) TaskExt * ext;
#endif

- (id) initWithBasic: (TaskBasic *) basic ext: (TaskExt *) ext;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (TaskBasic *) basic;
- (void) setBasic: (TaskBasic *) basic;
- (BOOL) basicIsSet;

- (TaskExt *) ext;
- (void) setExt: (TaskExt *) ext;
- (BOOL) extIsSet;

@end

@interface TaskListRequest : NSObject <NSCoding> {
  int __type;
  int64_t __lastid;
  int64_t __length;

  BOOL __type_isset;
  BOOL __lastid_isset;
  BOOL __length_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=type, setter=setType:) int type;
@property (nonatomic, getter=lastid, setter=setLastid:) int64_t lastid;
@property (nonatomic, getter=length, setter=setLength:) int64_t length;
#endif

- (id) initWithType: (int) type lastid: (int64_t) lastid length: (int64_t) length;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int) type;
- (void) setType: (int) type;
- (BOOL) typeIsSet;

- (int64_t) lastid;
- (void) setLastid: (int64_t) lastid;
- (BOOL) lastidIsSet;

- (int64_t) length;
- (void) setLength: (int64_t) length;
- (BOOL) lengthIsSet;

@end

@interface Msg : NSObject <NSCoding> {
  int64_t __sender;
  timestamp __time;
  NSString * __text;
  int __type;

  BOOL __sender_isset;
  BOOL __time_isset;
  BOOL __text_isset;
  BOOL __type_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=sender, setter=setSender:) int64_t sender;
@property (nonatomic, getter=time, setter=setTime:) timestamp time;
@property (nonatomic, retain, getter=text, setter=setText:) NSString * text;
@property (nonatomic, getter=type, setter=setType:) int type;
#endif

- (id) initWithSender: (int64_t) sender time: (timestamp) time text: (NSString *) text type: (int) type;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) sender;
- (void) setSender: (int64_t) sender;
- (BOOL) senderIsSet;

- (timestamp) time;
- (void) setTime: (timestamp) time;
- (BOOL) timeIsSet;

- (NSString *) text;
- (void) setText: (NSString *) text;
- (BOOL) textIsSet;

- (int) type;
- (void) setType: (int) type;
- (BOOL) typeIsSet;

@end

@interface FeedMsg : NSObject <NSCoding> {
  NSString * __sender;
  timestamp __time;
  int __type;
  NSString * __content;

  BOOL __sender_isset;
  BOOL __time_isset;
  BOOL __type_isset;
  BOOL __content_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=sender, setter=setSender:) NSString * sender;
@property (nonatomic, getter=time, setter=setTime:) timestamp time;
@property (nonatomic, getter=type, setter=setType:) int type;
@property (nonatomic, retain, getter=content, setter=setContent:) NSString * content;
#endif

- (id) initWithSender: (NSString *) sender time: (timestamp) time type: (int) type content: (NSString *) content;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) sender;
- (void) setSender: (NSString *) sender;
- (BOOL) senderIsSet;

- (timestamp) time;
- (void) setTime: (timestamp) time;
- (BOOL) timeIsSet;

- (int) type;
- (void) setType: (int) type;
- (BOOL) typeIsSet;

- (NSString *) content;
- (void) setContent: (NSString *) content;
- (BOOL) contentIsSet;

@end

@interface Summary : NSObject <NSCoding> {
  int64_t __unread_msg_num;
  int64_t __following_num;
  int64_t __followed_num;

  BOOL __unread_msg_num_isset;
  BOOL __following_num_isset;
  BOOL __followed_num_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=unread_msg_num, setter=setUnread_msg_num:) int64_t unread_msg_num;
@property (nonatomic, getter=following_num, setter=setFollowing_num:) int64_t following_num;
@property (nonatomic, getter=followed_num, setter=setFollowed_num:) int64_t followed_num;
#endif

- (id) initWithUnread_msg_num: (int64_t) unread_msg_num following_num: (int64_t) following_num followed_num: (int64_t) followed_num;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) unread_msg_num;
- (void) setUnread_msg_num: (int64_t) unread_msg_num;
- (BOOL) unread_msg_numIsSet;

- (int64_t) following_num;
- (void) setFollowing_num: (int64_t) following_num;
- (BOOL) following_numIsSet;

- (int64_t) followed_num;
- (void) setFollowed_num: (int64_t) followed_num;
- (BOOL) followed_numIsSet;

@end

@interface typeConstants : NSObject {
}
@end
