/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


enum enmSex {
  enmSex_MALE = 0,
  enmSex_FEMALE = 1,
  enmSex_UNKNOW = 2
};

typedef int64_t timestamp;

@interface AuthRequest : NSObject <NSCoding> {
  NSString * __client_id;
  NSString * __client_serect;

  BOOL __client_id_isset;
  BOOL __client_serect_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=client_id, setter=setClient_id:) NSString * client_id;
@property (nonatomic, retain, getter=client_serect, setter=setClient_serect:) NSString * client_serect;
#endif

- (id) initWithClient_id: (NSString *) client_id client_serect: (NSString *) client_serect;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) client_id;
- (void) setClient_id: (NSString *) client_id;
- (BOOL) client_idIsSet;

- (NSString *) client_serect;
- (void) setClient_serect: (NSString *) client_serect;
- (BOOL) client_serectIsSet;

@end

@interface AuthResponse : NSObject <NSCoding> {
  int64_t __uid;
  NSString * __name;
  NSString * __access_token;
  NSString * __refresh_token;
  int64_t __expire_time;

  BOOL __uid_isset;
  BOOL __name_isset;
  BOOL __access_token_isset;
  BOOL __refresh_token_isset;
  BOOL __expire_time_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=uid, setter=setUid:) int64_t uid;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=access_token, setter=setAccess_token:) NSString * access_token;
@property (nonatomic, retain, getter=refresh_token, setter=setRefresh_token:) NSString * refresh_token;
@property (nonatomic, getter=expire_time, setter=setExpire_time:) int64_t expire_time;
#endif

- (id) initWithUid: (int64_t) uid name: (NSString *) name access_token: (NSString *) access_token refresh_token: (NSString *) refresh_token expire_time: (int64_t) expire_time;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) uid;
- (void) setUid: (int64_t) uid;
- (BOOL) uidIsSet;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (NSString *) access_token;
- (void) setAccess_token: (NSString *) access_token;
- (BOOL) access_tokenIsSet;

- (NSString *) refresh_token;
- (void) setRefresh_token: (NSString *) refresh_token;
- (BOOL) refresh_tokenIsSet;

- (int64_t) expire_time;
- (void) setExpire_time: (int64_t) expire_time;
- (BOOL) expire_timeIsSet;

@end

@interface UserInfo : NSObject <NSCoding> {
  NSString * __name;
  int __sex;
  NSString * __org;
  NSString * __job;
  NSString * __small_avator;
  NSString * __big_avator;
  NSString * __intro;

  BOOL __name_isset;
  BOOL __sex_isset;
  BOOL __org_isset;
  BOOL __job_isset;
  BOOL __small_avator_isset;
  BOOL __big_avator_isset;
  BOOL __intro_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=sex, setter=setSex:) int sex;
@property (nonatomic, retain, getter=org, setter=setOrg:) NSString * org;
@property (nonatomic, retain, getter=job, setter=setJob:) NSString * job;
@property (nonatomic, retain, getter=small_avator, setter=setSmall_avator:) NSString * small_avator;
@property (nonatomic, retain, getter=big_avator, setter=setBig_avator:) NSString * big_avator;
@property (nonatomic, retain, getter=intro, setter=setIntro:) NSString * intro;
#endif

- (id) initWithName: (NSString *) name sex: (int) sex org: (NSString *) org job: (NSString *) job small_avator: (NSString *) small_avator big_avator: (NSString *) big_avator intro: (NSString *) intro;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (int) sex;
- (void) setSex: (int) sex;
- (BOOL) sexIsSet;

- (NSString *) org;
- (void) setOrg: (NSString *) org;
- (BOOL) orgIsSet;

- (NSString *) job;
- (void) setJob: (NSString *) job;
- (BOOL) jobIsSet;

- (NSString *) small_avator;
- (void) setSmall_avator: (NSString *) small_avator;
- (BOOL) small_avatorIsSet;

- (NSString *) big_avator;
- (void) setBig_avator: (NSString *) big_avator;
- (BOOL) big_avatorIsSet;

- (NSString *) intro;
- (void) setIntro: (NSString *) intro;
- (BOOL) introIsSet;

@end

@interface TaskInfo : NSObject <NSCoding> {
  int64_t __tid;
  NSString * __name;
  NSString * __intro;
  timestamp __begin_time;
  timestamp __end_time;
  int64_t __owner;
  NSArray * __user_apply_list;
  NSArray * __user_accept_list;
  NSArray * __user_reject_list;

  BOOL __tid_isset;
  BOOL __name_isset;
  BOOL __intro_isset;
  BOOL __begin_time_isset;
  BOOL __end_time_isset;
  BOOL __owner_isset;
  BOOL __user_apply_list_isset;
  BOOL __user_accept_list_isset;
  BOOL __user_reject_list_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=tid, setter=setTid:) int64_t tid;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=intro, setter=setIntro:) NSString * intro;
@property (nonatomic, getter=begin_time, setter=setBegin_time:) timestamp begin_time;
@property (nonatomic, getter=end_time, setter=setEnd_time:) timestamp end_time;
@property (nonatomic, getter=owner, setter=setOwner:) int64_t owner;
@property (nonatomic, retain, getter=user_apply_list, setter=setUser_apply_list:) NSArray * user_apply_list;
@property (nonatomic, retain, getter=user_accept_list, setter=setUser_accept_list:) NSArray * user_accept_list;
@property (nonatomic, retain, getter=user_reject_list, setter=setUser_reject_list:) NSArray * user_reject_list;
#endif

- (id) initWithTid: (int64_t) tid name: (NSString *) name intro: (NSString *) intro begin_time: (timestamp) begin_time end_time: (timestamp) end_time owner: (int64_t) owner user_apply_list: (NSArray *) user_apply_list user_accept_list: (NSArray *) user_accept_list user_reject_list: (NSArray *) user_reject_list;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) tid;
- (void) setTid: (int64_t) tid;
- (BOOL) tidIsSet;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (NSString *) intro;
- (void) setIntro: (NSString *) intro;
- (BOOL) introIsSet;

- (timestamp) begin_time;
- (void) setBegin_time: (timestamp) begin_time;
- (BOOL) begin_timeIsSet;

- (timestamp) end_time;
- (void) setEnd_time: (timestamp) end_time;
- (BOOL) end_timeIsSet;

- (int64_t) owner;
- (void) setOwner: (int64_t) owner;
- (BOOL) ownerIsSet;

- (NSArray *) user_apply_list;
- (void) setUser_apply_list: (NSArray *) user_apply_list;
- (BOOL) user_apply_listIsSet;

- (NSArray *) user_accept_list;
- (void) setUser_accept_list: (NSArray *) user_accept_list;
- (BOOL) user_accept_listIsSet;

- (NSArray *) user_reject_list;
- (void) setUser_reject_list: (NSArray *) user_reject_list;
- (BOOL) user_reject_listIsSet;

@end

@interface TaskSummary : NSObject <NSCoding> {
  NSArray * __recommend;
  NSArray * __nearby;
  NSArray * __follow;

  BOOL __recommend_isset;
  BOOL __nearby_isset;
  BOOL __follow_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=recommend, setter=setRecommend:) NSArray * recommend;
@property (nonatomic, retain, getter=nearby, setter=setNearby:) NSArray * nearby;
@property (nonatomic, retain, getter=follow, setter=setFollow:) NSArray * follow;
#endif

- (id) initWithRecommend: (NSArray *) recommend nearby: (NSArray *) nearby follow: (NSArray *) follow;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSArray *) recommend;
- (void) setRecommend: (NSArray *) recommend;
- (BOOL) recommendIsSet;

- (NSArray *) nearby;
- (void) setNearby: (NSArray *) nearby;
- (BOOL) nearbyIsSet;

- (NSArray *) follow;
- (void) setFollow: (NSArray *) follow;
- (BOOL) followIsSet;

@end

@interface typeConstants : NSObject {
}
@end
